### ISSUE TITLE
Implement calling Julia from q

### ISSUE THREAD

**Issue by abalkin** [abalkin/JuQ.jl#6]
## References

  * [JuliaPy/pyjulia](/JuliaPy/pyjulia)
  * [File locations](https://docs.julialang.org/en/latest/manual/environment-variables/#File-locations-1)
  * [Using julia-config in Makefiles](https://docs.julialang.org/en/latest/manual/embedding/#Use-in-Makefiles-1)

## TODO

  1. [x] Implement `J)` language for kdb+.  #7.
  1. [x] Install q components in `Pkg.build("JuQ")`. #8.
  1. [x] Detect presence kdb+ symbols in executable and don't load `c.so`.  #10.
  1. [x] Rethrow exceptions and convert some returned scalar values. #29.

Locating libjulia:

```
julia> Libdl.dlpath("libjulia")
"/Applications/Julia-0.6.app/Contents/Resources/julia/lib/libjulia.0.6.0.dylib"
```

Also

```
julia> JULIA_HOME
"/Applications/Julia-0.6.app/Contents/Resources/julia/bin"

julia> LOAD_PATH
2-element Array{Any,1}:
 "/Applications/Julia-0.6.app/Contents/Resources/julia/local/share/julia/site/v0.6"
 "/Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/site/v0.6"
```

**Comment by abalkin** [comment]
Julia should be able to create an object callable from q by creating a C ABI function and passing a pointer to it to `dl()`. See ["Creating C-Compatible Julia Function Pointers"](https://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#Creating-C-Compatible-Julia-Function-Pointers-1).

**Comment by abalkin** [comment]
#41 demonstrates feasibility of creating q functions by calling `dl` and `cfunction` on Julia functions.   Making this convenient (define `convert(K, x::Function)`?) is left for another issue.
